'use strict';

const PDFKit = require('pdfkit');
const { v4: uuidv4 } = require('uuid');
const { getDb } = require('../db/connection');

/**
 * Create a receipt record for a payment ledger entry.
 *
 * The sequence number read and the INSERT are one SQLite transaction so two
 * concurrent async calls (fired after two near-simultaneous 201 responses)
 * cannot both observe the same last-seq and then collide on UNIQUE
 * (receipt_number). better-sqlite3 transactions are synchronous and exclusive:
 * the event loop cannot interleave a second call between the SELECT and the
 * INSERT inside the same transaction body.
 *
 * Returns the created receipt object, the pre-existing one if it already
 * exists, or null if the payment row is gone.
 */
async function generateReceipt({ db: passedDb, paymentId, propertyId, residentId, actorId }) {
  const db = passedDb || getDb();

  // Fast-path: already receipted (handles retries and double-calls)
  const existing = db.prepare('SELECT * FROM receipts WHERE payment_ledger_id = ?').get(paymentId);
  if (existing) return existing;

  const payment = db.prepare('SELECT * FROM payment_ledger WHERE id = ?').get(paymentId);
  if (!payment) return null;

  const lineItems = [
    {
      description: `${payment.type.replace('_', ' ')} — ${payment.billing_month || 'N/A'}`,
      amount_paise: payment.amount_paise,
    },
  ];

  const id  = uuidv4();
  const now = new Date().toISOString();

  // Atomic: read last seq + compute next + INSERT, all inside one exclusive tx.
  // No other async task can read the same last-seq before this INSERT commits.
  const receipt = db.transaction(() => {
    const prop = db.prepare('SELECT property_code FROM properties WHERE id = ?').get(propertyId);
    const code = (prop?.property_code || 'PROP').toUpperCase();
    const ym   = (payment.billing_month || now.substring(0, 7)).replace('-', '');

    const last = db.prepare(`
      SELECT receipt_number FROM receipts
      WHERE property_id = ? AND receipt_number LIKE ?
      ORDER BY created_at DESC LIMIT 1
    `).get(propertyId, `DB-${code}-${ym}-%`);

    let seq = 1;
    if (last) {
      seq = parseInt(last.receipt_number.split('-').pop(), 10) + 1;
    }
    const receiptNumber = `DB-${code}-${ym}-${String(seq).padStart(4, '0')}`;

    db.prepare(`
      INSERT INTO receipts
        (id, property_id, resident_id, payment_ledger_id, receipt_number,
         amount_paise, line_items, wa_delivered, created_at)
      VALUES (?, ?, ?, ?, ?, ?, ?, 0, ?)
    `).run(id, propertyId, residentId, paymentId, receiptNumber,
      payment.amount_paise, JSON.stringify(lineItems), now);

    return db.prepare('SELECT * FROM receipts WHERE id = ?').get(id);
  })();

  return receipt;
}

/**
 * Generate a PDF buffer for a receipt.
 */
async function generateReceiptPdf(receipt) {
  return new Promise((resolve, reject) => {
    try {
      const doc    = new PDFKit({ size: [226, 500], margin: 16 }); // 80mm thermal
      const chunks = [];
      doc.on('data', c => chunks.push(c));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      const lineItems = typeof receipt.line_items === 'string'
        ? JSON.parse(receipt.line_items) : receipt.line_items || [];

      doc.fontSize(12).font('Helvetica-Bold').text(receipt.property_name || 'DormBook', { align: 'center' });
      doc.fontSize(8).font('Helvetica').text(receipt.property_address || '', { align: 'center' });
      doc.moveDown(0.5);
      doc.fontSize(10).font('Helvetica-Bold').text('PAYMENT RECEIPT', { align: 'center' });
      doc.moveTo(16, doc.y).lineTo(210, doc.y).stroke();
      doc.moveDown(0.3);
      doc.fontSize(8).font('Helvetica');
      doc.text(`Receipt No: ${receipt.receipt_number}`);
      doc.text(`Date: ${new Date(receipt.created_at).toLocaleDateString('en-IN')}`);
      doc.text(`Resident: ${receipt.resident_name}`);
      doc.text(`Mobile: ${receipt.resident_mobile}`);
      doc.moveDown(0.5);
      doc.moveTo(16, doc.y).lineTo(210, doc.y).stroke();
      doc.moveDown(0.3);

      lineItems.forEach(item => {
        doc.text(item.description, { continued: true });
        doc.text(`₹${(item.amount_paise / 100).toFixed(2)}`, { align: 'right' });
      });

      doc.moveDown(0.3);
      doc.moveTo(16, doc.y).lineTo(210, doc.y).stroke();
      doc.moveDown(0.3);
      doc.fontSize(9).font('Helvetica-Bold');
      doc.text('TOTAL', { continued: true });
      doc.text(`₹${(receipt.amount_paise / 100).toFixed(2)}`, { align: 'right' });
      doc.moveDown(0.5);
      doc.fontSize(7).font('Helvetica').text('Thank you for your payment.', { align: 'center' });
      doc.text('Generated by DormBook', { align: 'center' });
      doc.end();
    } catch (err) {
      reject(err);
    }
  });
}

module.exports = { generateReceipt, generateReceiptPdf };
